In [1]:
#import the required libraries
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Step 1 : Read the Data!

In [2]:
#give path of the source-file and store that path in a variable named census
#census = np.genfromtxt('', delimiter=',')
census = '/content/drive/My Drive/Data for Pandas/makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [3]:
data = np.genfromtxt(census, delimiter = ',' , skip_header = 1 )
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

# Printing the type of data

In [96]:
#print the type of data
print("Type of data is: ",data.dtype)

Type of data is:  int64


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [97]:
new_record = [[50,9,4,1,0,0,40,0]]


## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [98]:
new_record_array = np.array(new_record)

# Concatenate the new row to the existing array (axis=0 for row-wise concatenation)
result = np.concatenate((data, new_record_array), axis=0)

In [100]:
#display after appending the new record at the end of the array.
print("Data after appending the new record")
print(result)

Data after appending the new record
[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]


# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [101]:
age = data[:, 0]
print("Column of age only: ")
age

Column of age only: 


array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 37, 30, 23, 32, 40, 34, 25,
       32, 38, 43, 40, 54, 35, 43, 59, 56, 19, 54, 39, 49, 23, 20, 45, 30,
       22, 48, 21, 19, 31, 48, 31, 53, 24, 49, 25, 57, 53, 44, 41, 29, 25,
       18, 47, 50, 47, 43, 46, 35, 41, 30, 30, 32, 48, 42, 29, 36, 28, 53,
       49, 25, 19, 31, 29, 23, 79, 27, 40, 67, 18, 31, 18, 52, 46, 59, 44,
       53, 49, 33, 30, 43, 57, 37, 28, 30, 34, 29, 48, 37, 48, 32, 76, 44,
       47, 20, 29, 32, 17, 30, 31, 42, 24, 38, 56, 28, 36, 53, 56, 49, 55,
       22, 21, 40, 30, 29, 19, 47, 20, 31, 35, 39, 28, 24, 38, 37, 46, 38,
       43, 27, 20, 49, 61, 27, 19, 45, 70, 31, 22, 36, 64, 43, 47, 34, 33,
       21, 52, 48, 23, 71, 29, 42, 68, 25, 44, 28, 45, 36, 39, 46, 18, 66,
       27, 28, 51, 27, 28, 27, 21, 34, 18, 33, 44, 43, 30, 40, 37, 34, 41,
       53, 31, 58, 38, 24, 41, 47, 41, 23, 36, 40, 35, 24, 26, 19, 51, 42,
       37, 18, 36, 35, 58, 17, 44, 37, 35, 60, 54, 37, 50, 38, 45, 25, 31,
       64, 90, 54, 53, 18

Find the max age and store it in a variable called 'max_age'.



In [103]:
#print the max_age
max_age = np.max(age)
print("Oldest people have age of:", max_age, "years")

Oldest person has age of: 90 years


Find the min age and store it in a variable called 'min_age'.

In [104]:
#print the min_age
min_age = np.min(age)
print("Youngest people have age of:", min_age, "years")

Youngest people have age of: 17 years


Find the mean of the age and store it in a variable called 'age_mean'.

In [105]:
#print the age_mean
mean_age = np.mean(age)
print("Mean or average of age is:", mean_age)

Mean or average of age is: 38.051


Find the standard deviation of the age and store it in a variable called 'age_std'

In [106]:
#print the age_std
age_std = np.std(age)
print("Standard Deviation of the age is:", age_std)

Standard Deviation of the age is: 13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [109]:
race_0 = data[data[:, 2] == 0]
print("Race 0 Data")
print(race_0)
race_1 = data[data[:, 2] == 1]
print("Race 1 Data")
print(race_1)
race_2 = data[data[:, 2] == 2]
print("Race 2 Data")
print(race_2)
race_3 = data[data[:, 2] == 3]
print("Race 3 Data")
print(race_3)
race_4 = data[data[:, 2] == 4]
print("Race 4 Data")
print(race_4)

Race 0 Data
[[34  4  0  1  0  0 45  0]
 [35 10  0  0  0  0 40  0]
 [60  6  0  0  0  0 10  0]
 [51  9  0  1  0  0 40  0]
 [25 10  0  0  0  0 20  0]
 [20  9  0  1  0  0 48  0]
 [23 10  0  0  0  0 25  0]
 [29  9  0  1  0  0 40  0]
 [27 12  0  1  0  0 40  0]
 [31 12  0  0  0  0 40  0]]
Race 1 Data
[[  30   13    1    1    0    0   40    1]
 [  40   11    1    1    0    0   40    1]
 [  54   10    1    1    0    0   60    1]
 [  30    9    1    0    0 1573   35    0]
 [  49   10    1    1    0    0   40    1]
 [  33   13    1    0    0    0   40    0]
 [  44   14    1    0    0    0   40    0]
 [  28    9    1    0    0    0   40    0]
 [  60    9    1    1    0    0   40    0]
 [  42    9    1    1    0    0   40    1]
 [  37   10    1    1    0    0   75    1]
 [  39   14    1    0 3464    0   40    0]
 [  21   10    1    0    0    0   25    0]
 [  24   10    1    0    0    0   40    0]
 [  34   14    1    1 7298    0   35    1]
 [  27   10    1    1    0 1980   40    0]
 [  40   11    1 

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [91]:
#len_0
len_0 = race_0.shape[0]
print("Length of race 0: ", len_0)

Length of race 0:  10


In [92]:
#len_1
len_1 = race_1.shape[0]
print("Length of race 1: ", len_1)

Length of race 1:  27


In [93]:
#len_2
len_2 = race_2.shape[0]
print("Length of race 2: ", len_2)

Length of race 2:  110


In [94]:
#len_3
len_3 = race_3.shape[0]
print("Length of race 3: ", len_3)

Length of race 3:  6


In [95]:
#len_4
len_4 = race_4.shape[0]
print("Length of race 4: ", len_4)

Length of race 4:  847


Find out which is the race with the minimum no. of citizens

In [110]:
race = data[:, 2]
min_race = np.min(race)
print("Race with minimum number of citizens:", min_race)

Race with minimum number of citizens: 0


Find out which is the race with the minimum no. of citizens

In [111]:
race = data[:, 2]
min_race = np.min(race)
print("Race with minimum number of citizens:", min_race)

Race with minimum number of citizens: 0


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [124]:
minority_race = np.min(race)
print("Minority Race:", minority_race)

Minority Race: 0


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race = np.min(race)
minority_race

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [112]:
#from age column, filter out age data > 60
indices = np.where(data[:, 0] > 60)
senior_citizens = data[indices]
print("The following is the data of senior citizens:")
senior_citizens

The following is the data of senior citizens:


array([[   79,    10,     4,     1,     0,     0,    20,     0],
       [   67,     6,     4,     1,     0,     0,     2,     0],
       [   76,    14,     4,     1,     0,     0,    40,     1],
       [   61,     9,     4,     1,     0,     0,    40,     0],
       [   70,    10,     4,     1,     0,     0,    40,     0],
       [   64,     7,     4,     1,     0,  2179,    40,     0],
       [   71,    10,     2,     1,     0,  1816,     2,     0],
       [   68,     2,     4,     0,     0,     0,    20,     0],
       [   66,    11,     4,     0,     0,     0,    20,     0],
       [   64,     2,     4,     1,     0,     0,    40,     0],
       [   90,     9,     2,     1,     0,  2206,    40,     0],
       [   66,     9,     4,     1,  1409,     0,    50,     0],
       [   75,    11,     4,     0,     0,     0,    20,     0],
       [   65,     9,     4,     0,     0,     0,    40,     0],
       [   64,     9,     4,     1,     0,     0,    40,     1],
       [   61,     9,    

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [84]:
working_hours_sum = np.sum(senior_citizens[:, 6])
print ("Sum of working hours of senior citizens:", working_hours_sum)

Sum of working hours: 1917


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [85]:
#senior_citizens_len = len(senior_citizens)
senior_citizens_len = senior_citizens.shape[0]
print("Total number of senior senior citizens: ",senior_citizens_len)

Total number of senior senior citizens:  61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [86]:
avg_working_hours = working_hours_sum / senior_citizens_len
print("Average Working Hours: ", avg_working_hours)

Average Working Hours:  31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [113]:
print("Average Working Hours: ", avg_working_hours)
govt_policy = senior_citizens[senior_citizens[:, 6] > 25]

if len(govt_policy) > 0:
    print("Government Policies are not being followed by:")
    print(govt_policy)
else:
    print("The Government Policy is being followed.")

Average Working Hours:  31.42622950819672
Government Policies are not being followed by:
[[   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   77    10     4     1     0     0    40     0]
 [   63     9     4     1     0     0    45     0]
 [   66     9     4     1  2050     0    55     0]
 [   65     7     3     1     0     0    40     0]
 [   62    14     4     1     0     0    40     1]
 [   63     9     4     1     0     0    40     1]
 [   63     2     4     1     0     0    35     0]
 [   62     9     4     1     0     0    40 

# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [115]:
high = data[data[:, 1] > 10]
print("Higher Educated People are:")
print(high)
low = data[data[:, 1] <= 10]
print("Lower Educated People are:")
print(low)

Higher Educated People are:
[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [45 14  4 ...  0 45  0]
 [48 13  4 ...  0 58  1]
 [39 13  4 ...  0 50  1]]
Lower Educated People are:
[[38  9  4 ...  0 40  0]
 [53  7  2 ...  0 40  0]
 [49  5  2 ...  0 16  0]
 ...
 [35  9  4 ...  0 45  0]
 [56  9  4 ...  0 55  1]
 [40 10  4 ...  0 40  0]]


Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [118]:
if high.size > 0:
  avg_pay_high = np.mean(high[:, 7])
  print("Average pay of highly educated people:", avg_pay_high)
else: 0

if low.size > 0:
  avg_pay_low = np.mean(low[:, 7])
  print("Average pay of low educated people", avg_pay_low)
else: 0

Average pay of highly educated people: 0.42813455657492355
Average pay of low educated people 0.13670133729569092


In [119]:
if avg_pay_high > avg_pay_low:
  print("Higher education correlates with higher income.")
else:
  print("No higher education does not correlates with higher income.")

Higher education correlates with higher income.
