In [1]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [ ]:
array1 = np.random.randint(0, 100, size=(2,3,4))
print(array1)
sum = np.sum(array1)

print("Sum of all elements in the array: ", sum)

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [ ]:
array2 = np.random.randint(0, 10, size=(2, 3, 4, 5))
print(array2)


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [11]:
array3 = np.random.randint(0, 10, size=(2, 3, 4, 5))
mean = np.mean(array3, axis=1)

print("Mean: ", mean)


Mean:  [[[3.66666667 1.66666667 5.66666667 4.66666667 5.33333333]
  [1.         6.33333333 6.         3.66666667 1.33333333]
  [3.66666667 6.33333333 4.66666667 5.66666667 4.33333333]
  [6.66666667 6.33333333 5.66666667 1.33333333 5.66666667]]

 [[5.33333333 5.33333333 5.66666667 3.66666667 3.33333333]
  [6.33333333 5.         0.66666667 3.         5.33333333]
  [3.         3.         5.66666667 5.66666667 6.66666667]
  [7.         2.         5.33333333 4.66666667 4.        ]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [10]:
temps = np.random.rand(7, 24, 60) * 100
average_temps_per_day = np.mean(temps, axis=(1, 2))


print("Average temperatures for each day:", average_temps_per_day)


Average temperatures for each day: [51.64017509 49.25382862 48.84904814 49.867323   50.32053184 49.50481767
 50.89926101]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [13]:
import numpy as np
readings = np.random.randint(0, 100, size=(4, 7, 24, 60))
max_readings = np.max(readings, axis=1)

print("Maximum readings for each sensor across all days: ", max_readings)

Maximum readings for each sensor across all days:  [[[95 91 86 ... 99 93 83]
  [91 81 96 ... 97 97 84]
  [80 98 82 ... 93 97 85]
  ...
  [95 76 79 ... 92 92 95]
  [70 96 94 ... 78 88 87]
  [91 83 96 ... 79 95 80]]

 [[81 96 86 ... 96 98 91]
  [96 90 85 ... 64 87 93]
  [87 99 98 ... 98 92 72]
  ...
  [76 70 92 ... 87 83 93]
  [96 97 91 ... 82 92 98]
  [95 99 90 ... 92 97 75]]

 [[73 72 71 ... 93 95 96]
  [90 96 88 ... 75 99 91]
  [86 98 98 ... 88 84 87]
  ...
  [78 93 83 ... 80 85 99]
  [98 81 86 ... 93 66 76]
  [99 80 88 ... 94 97 93]]

 [[77 90 93 ... 79 96 72]
  [75 67 82 ... 90 98 97]
  [99 97 76 ... 91 86 90]
  ...
  [85 92 87 ... 84 94 92]
  [56 67 87 ... 95 99 56]
  [97 59 97 ... 85 79 99]]]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [22]:
array6 = np.random.randint(1, 100, size=(100, 50, 3))
average_dimensions = np.mean(array6, axis=(0, 1))
average_length, average_width, average_height = average_dimensions

print("Average Length: ", average_length)
print("Average Width: ", average_width)
print("Average Height: ", average_height)


Average Length:  49.6724
Average Width:  50.0592
Average Height:  49.3954


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [ ]:
# Answer Here


In [25]:
a = np.random.randint(0, 100, size=(5, 6, 7))

num_sensors = a.shape[0] * a.shape[1]
results = np.empty((num_sensors, 5))

index = 0
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        measurements = a[i, j, :]

        total_measurements = measurements.size
        avg_measurement = np.mean(measurements)
        std_measurement = np.std(measurements)
        min_measurement = np.min(measurements)
        max_measurement = np.max(measurements)

        results[index] = [total_measurements, avg_measurement, std_measurement, min_measurement, max_measurement]
        index += 1

for sensor_id in range(num_sensors):
    print("Sensor : ", sensor_id + 1)
    print("  Total Measurements: ", int(results[sensor_id][0]))
    print("  Average Value: ", int(results[sensor_id][1]))
    print("  Standard Deviation: ", results[sensor_id][2])
    print("  Minimum Value: ", int(results[sensor_id][3]))
    print("  Maximum Value: ", int(results[sensor_id][4]))

Sensor :  1
  Total Measurements:  7
  Average Value:  48
  Standard Deviation:  24.446526400722547
  Minimum Value:  8
  Maximum Value:  83
Sensor :  2
  Total Measurements:  7
  Average Value:  57
  Standard Deviation:  24.465719457465962
  Minimum Value:  18
  Maximum Value:  96
Sensor :  3
  Total Measurements:  7
  Average Value:  56
  Standard Deviation:  10.61573725894817
  Minimum Value:  39
  Maximum Value:  77
Sensor :  4
  Total Measurements:  7
  Average Value:  37
  Standard Deviation:  26.4328181916159
  Minimum Value:  4
  Maximum Value:  75
Sensor :  5
  Total Measurements:  7
  Average Value:  50
  Standard Deviation:  25.511102025012804
  Minimum Value:  10
  Maximum Value:  91
Sensor :  6
  Total Measurements:  7
  Average Value:  38
  Standard Deviation:  28.956688276085153
  Minimum Value:  3
  Maximum Value:  93
Sensor :  7
  Total Measurements:  7
  Average Value:  54
  Standard Deviation:  25.223895376392274
  Minimum Value:  1
  Maximum Value:  87
Sensor :  8
 