In [ ]:
import numpy as np

### Basic Array Creation

# Creatation of List
create List in python? # Check Type of list

In [ ]:
list1 = [8,2,0,9,1]
ltype = type(list1)

print ("The list ", list1, "has type", ltype)

The list  [8, 2, 0, 9, 1] has type <class 'list'>


# Creatation of Arrays
1.Create an array containing 10 elements

2.Checking array "TYPE"

3.Check data type of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.Total bytes in an Array

In [ ]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
print("1. Integer Array containing 10 elements",array1)
print("2. Type of array is: ", type(array1))
dt_of_elements = [type(element) for element in array1]
print("3. Data type of array elements is: ", dt_of_elements)
print("4. Array dimension is: ", array1.ndim)
print("5. Array shape is: ", array1.shape)
print("6. Array Bytes per elements are: ", array1.itemsize)
print("7. Total Bytes: ", array1.nbytes)

1. Array containing 10 elements [0 1 2 3 4 5 6 7 8 9]
2. Type of array is:  <class 'numpy.ndarray'>
3. Data type of array elements is:  [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]
4. Array dimension is:  1
5. Array shape is:  (10,)
6. Array Bytes per elements are:  8
7. Total Bytes:  80


In [ ]:
array2 = np.array([0,2.1,22.1,5.3,41.4,7.5,98.6,7.9,8.0,80.9])
print("1. Float Array containing 10 elements",array2)
print("2. Type of array is: ", type(array2))
dt_of_elements = [type(element) for element in array2]
print("3. Data type of array elements is: ", dt_of_elements)
print("4. Array dimension is: ", array2.ndim)
print("5. Array shape is: ", array2.shape)
print("6. Array Bytes per elements are: ", array2.itemsize)
print("7. Total Bytes: ", array2.nbytes)

1. Float Array containing 10 elements [ 0.   2.1 22.1  5.3 41.4  7.5 98.6  7.9  8.  80.9]
2. Type of array is:  <class 'numpy.ndarray'>
3. Data type of array elements is:  [<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]
4. Array dimension is:  1
5. Array shape is:  (10,)
6. Array Bytes per elements are:  8
7. Total Bytes:  80


-Try to assign a float into an int32

-Use .fill function # fill has the same behavior


In [77]:
int_array = np.array([1,2,3,4,5], dtype=np.int32)
int_array[3] = 5.2
print("Assign a float to int32", int_array)

int_array.fill(4.3)
print("Fill function: ",int_array)


Assign a float to int32 [1 2 3 5 5]
Fill function:  [4 4 4 4 4]


-. Add two  arrays

-. Multiple both arrays

-.Use ** operator in array operation

-.Create array from 0.0 to 11.0

-.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

-.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [80]:
a = np.array([0,1,2,3,4])
b = np.array([4,5,6,7,8])
print("1. Addition of arrays a and b is: ", a+b)
print("2. Multiplication of arrays a and b is: ", a*b)
print("3. a power b is: ", a**b)
array3 = np.arange(12.0)
print("4. Array from 0.0 to 11.0 ", array3)
print("5. Multiply with scalar value c = (2.0 * np.pi)", array3*(2.0*np.pi/10.0))
array4 = np.arange(1.0, 3.0, 0.5)
print("6. Array using np.arange ",array4)

1. Addition of arrays a and b is:  [ 4  6  8 10 12]
2. Multiplication of arrays a and b is:  [ 0  5 12 21 32]
3. a power b is:  [    0     1    64  2187 65536]
4. Array from 0.0 to 11.0  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
5. Multiply with scalar value c = (2.0 * np.pi) [0.         0.62831853 1.25663706 1.88495559 2.51327412 3.14159265
 3.76991118 4.39822972 5.02654825 5.65486678 6.28318531 6.91150384]
6. Array using np.arange  [1.  1.5 2.  2.5]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [82]:
from types import new_class
array5 = np.array([0,1,2,3,4,5,6,7,8,9])
print("1.", array5[1:3])
print("2.", array5[-9:-7])
print("3.", array5[-10:-7])
print("4.", array5[8:11])
print("5.", array5[::2])
print("6.", array5[-2:])
# yes iterable at index 5 for example
n = [100,200]
iterate = np.insert(array5, 5, n)
print("7.", iterate)
# or insert scalar value at index 5
s = 19
insert = np.insert(array5, 5, s)
print("7.", insert)
b = array5[0:3]
b[0] = 4
b[1] = 8
b[2] = 16
print("8.", array5)
array6 = np.array([[0,1,2,3,4],[1,2,3,4,5]])
print("9.", array6[1, ::2])

1. [1 2]
2. [1 2]
3. [0 1 2]
4. [8 9]
5. [0 2 4 6 8]
6. [8 9]
7. [  0   1   2   3   4 100 200   5   6   7   8   9]
7. [ 0  1  2  3  4 19  5  6  7  8  9]
8. [ 4  8 16  3  4  5  6  7  8  9]
9. [1 3 5]


In [84]:
array7 = np.arange(0,36).reshape(6,6)
mask = np.array([1,0,1,0,0,1], dtype=bool)
masked_a = array7[mask]
print("10. ")
print(masked_a)

10. 
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [30 31 32 33 34 35]]


### Now use indexing to select the 5th 7th and 11th columns

In [71]:
array8 = np.arange(0,225).reshape(15,15)
array8[:,[4,6,10]]

array([[  4,   6,  10],
       [ 19,  21,  25],
       [ 34,  36,  40],
       [ 49,  51,  55],
       [ 64,  66,  70],
       [ 79,  81,  85],
       [ 94,  96, 100],
       [109, 111, 115],
       [124, 126, 130],
       [139, 141, 145],
       [154, 156, 160],
       [169, 171, 175],
       [184, 186, 190],
       [199, 201, 205],
       [214, 216, 220]])

### Select the 2nd row and fourth-last to second-last columns

In [72]:
array8[1, -4:-1]

array([26, 27, 28])

### Select 3rd to 3rd last columns skipping every second column

In [73]:
array8[:, 2:-3:2]

array([[  2,   4,   6,   8,  10],
       [ 17,  19,  21,  23,  25],
       [ 32,  34,  36,  38,  40],
       [ 47,  49,  51,  53,  55],
       [ 62,  64,  66,  68,  70],
       [ 77,  79,  81,  83,  85],
       [ 92,  94,  96,  98, 100],
       [107, 109, 111, 113, 115],
       [122, 124, 126, 128, 130],
       [137, 139, 141, 143, 145],
       [152, 154, 156, 158, 160],
       [167, 169, 171, 173, 175],
       [182, 184, 186, 188, 190],
       [197, 199, 201, 203, 205],
       [212, 214, 216, 218, 220]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [74]:
array8[:, 2:-3:2][:, ::-1]

array([[ 10,   8,   6,   4,   2],
       [ 25,  23,  21,  19,  17],
       [ 40,  38,  36,  34,  32],
       [ 55,  53,  51,  49,  47],
       [ 70,  68,  66,  64,  62],
       [ 85,  83,  81,  79,  77],
       [100,  98,  96,  94,  92],
       [115, 113, 111, 109, 107],
       [130, 128, 126, 124, 122],
       [145, 143, 141, 139, 137],
       [160, 158, 156, 154, 152],
       [175, 173, 171, 169, 167],
       [190, 188, 186, 184, 182],
       [205, 203, 201, 199, 197],
       [220, 218, 216, 214, 212]])

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]


In [ ]:
sum = []
for x, y in zip(a, b):
    sum.append(x + y)
print(sum)

[3, 5, 7, 9]
