# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [7]:
import numpy as np
a = np.arange(-25, 25, 2).reshape(5,5)
print(a)

[[-25 -23 -21 -19 -17]
 [-15 -13 -11  -9  -7]
 [ -5  -3  -1   1   3]
 [  5   7   9  11  13]
 [ 15  17  19  21  23]]


2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [11]:
shape = (3, 3)
ones_array_int = np.ones(shape, dtype=int)
print(ones_array_int)

zeros_array_float32 = np.zeros(shape, dtype=np.float32)
print(zeros_array_float32)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3.Generate an n by n identity array. The default dtype is float64.

1.   List item

1.   List item
2.   List item


2.   List item



In [12]:
array2 = np.identity(5)
print(array2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [15]:
array2 = np.arange(0, 25).reshape(5, 5)

empty_array = np.empty((5, 5))
print("Empty Array: ")
print(empty_array)

full_array = np.full((5, 5), 7)
print("Full Array :")
print(full_array)
filled_array = array2.copy()
filled_array.fill(10)
print("Array after fill: ")
print(filled_array)
max_value = np.max(array2)
min_value = np.min(array2)
std_value = np.std(array2)
mean_value = np.mean(array2)
var_value = np.var(array2)
argmax_value = np.argmax(array2)
linspace_array = np.linspace(0, 1, 5)

print("\nStatistics of array2:")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Standard Deviation: {std_value}")
print(f"Mean: {mean_value}")
print(f"Variance: {var_value}")
print(f"Index of Max Value: {argmax_value}")
print("\nLinspace Array (5 values between 0 and 1):")
print(linspace_array)


Empty Array: 
[[144. 121. 100.  81.  64.]
 [ 49.  36.  25.  16.   9.]
 [  4.   1.   0.   1.   4.]
 [  9.  16.  25.  36.  49.]
 [ 64.  81. 100. 121. 144.]]
Full Array :
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Array after fill: 
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

Statistics of array2:
Max: 24
Min: 0
Standard Deviation: 7.211102550927978
Mean: 12.0
Variance: 52.0
Index of Max Value: 24

Linspace Array (5 values between 0 and 1):
[0.   0.25 0.5  0.75 1.  ]


5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [16]:
import numpy as np
from scipy.stats import skew, kurtosis

# Create the array
array3 = np.arange(0, 25).reshape(5, 5)

# Mean
mean = np.mean(array3)
print("Mean:", mean)

# Standard Deviation
std = np.std(array3)
print("Standard Deviation:", std)

# Skewness
skew = skew(array3, axis=None)
print("Skewness:", skew)

# Kurtosis
kurt = kurtosis(array3, axis=None)
print("Kurtosis:", kurt)

# Sum
sum = np.sum(array3)
print("Sum:", sum)

# Product
prod = np.prod(array3)
print("Product:", prod)


Mean: 12.0
Standard Deviation: 7.211102550927978
Skewness: 0.0
Kurtosis: -1.2038461538461538
Sum: 300
Product: 0


6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [ ]:
array4 = np.arange(-15,15).reshape(5,6)**2
print("1. The maximum of each row is: ")
array4.max(axis=-1)
print("2. The mean of each column is: ")
array4.mean(axis=0)
print("3. The position of the overall minimum: ")
mindex = np.argmin(array4)
row, col = np.unravel_index(mindex, array4.shape)
print(row,col)

1. The maximum of each row is: 
2. The mean of each column is: 
3. The position of the overall minimum: 
2 3


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [ ]:
array5 = np.random.rand(5,4)*10
array6 = np.random.rand(5)*10

new_array6 = array6[:, np.newaxis]

print("Arrays are: ", array5, " ", array6)
print("Addition is: ", array5 + new_array6)
print("Subtraction is: ", array5 - new_array6)

Arrays are:  [[1.44582835 3.73609355 1.55413532 5.93837716]
 [2.1302312  7.94379101 4.86041662 7.30478755]
 [4.54925868 2.43246427 5.82285829 2.10753377]
 [7.24972222 8.2944655  6.43204648 0.76410026]
 [8.99681154 4.47306835 6.30169732 0.44991227]]   [9.47894813 0.05425113 0.1878259  6.47547166 6.64475455]
Addition is:  [[10.92477648 13.21504168 11.03308345 15.41732529]
 [ 2.18448233  7.99804214  4.91466775  7.35903868]
 [ 4.73708458  2.62029017  6.0106842   2.29535968]
 [13.72519388 14.76993716 12.90751814  7.23957191]
 [15.64156609 11.11782289 12.94645187  7.09466682]]
Subtraction is:  [[-8.03311978 -5.74285458 -7.92481281 -3.54057097]
 [ 2.07598007  7.88953988  4.80616549  7.25053642]
 [ 4.36143277  2.24463836  5.63503239  1.91970787]
 [ 0.77425057  1.81899384 -0.04342517 -5.7113714 ]
 [ 2.352057   -2.1716862  -0.34305722 -6.19484227]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [ ]:
x = np.array([1,2,3,4])
y = np.add.reduce(x)
print(y)

z = np.add.accumulate(x)
print(z)


10
[ 1  3  6 10]


### We will work with the following array:

In [ ]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Use slicing only to select 3rd and last row along with 2nd and last columns

In [ ]:
print(a[[2, -1], [1, -1]])


[11 24]


# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [ ]:
print(a[[0, 2, -1], 2:4])

[[ 2  3]
 [12 13]
 [22 23]]


# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [ ]:
#print(a[[1, 3, 4], 1:3])
a[[1,3,4], :][:, [1,3]]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

# Change the values 1, 10, 19 and 22 in the array to -2

In [ ]:
a = np.arange(25).reshape(5, 5)
a[a==1] = -2
a[a==10] = -2
a[a==19] = -2
a[a==22] = -2
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


# Repeat above using boolean indexing

In [17]:
mask = (a == 1)
mask = (a == 10)
mask = (a == 19)
mask = (a == 22)
a[mask] = -2


# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [ ]:
a = np.arange(25).reshape(5, 5)
rmask = np.array([True, False, True, True, False])
print( a[rmask, :][:, [0, 3]])


[[ 0  3]
 [10 13]
 [15 18]]


# Calculating the sum, min and max of all diagonal values

In [ ]:
diagonal = np.diagonal(a)
print("Sum: ", np.sum(diagonal))
print("Min: ", np.min(diagonal))
print("Max: ", np.max(diagonal))

Sum:  60
Min:  0
Max:  24


# Calculate the sum of differences between the 2nd row and 2nd last column

1.   List item
2.   List item



In [ ]:
second_row = a[1, :]
second_last_column = a[:, -2]
differences = second_row - second_last_column
sum_of_dif = np.sum(differences)
print(sum_of_dif)

-30


# Create a new array that is the sum of even rows and odd rows

In [22]:
array7 = np.arange(25).reshape(5, 5)
sum_of_even = array7[::2].sum(axis=0)

print("Sum of even rows is : ", np.sum(sum_of_even))

sum_of_odd = array7[1::2].sum(axis=0)

print("Sum of odd rows is : ", np.sum(sum_of_odd))

new_array = np.array([np.sum(sum_of_even), np.sum(sum_of_odd)])
print("New array is: ", new_array)


Sum of even rows is :  180
Sum of odd rows is :  120
New array is:  [180 120]


## You are done. Good job!